name: CI/CD Pipeline with Security Checks

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

  security-checks:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # SAST (Semgrep)
      - name: Run SAST (Semgrep)
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true  # Não quebra o build
        with:
          config: p/java
          output: semgrep-results.sarif

      # SCA (Dependency Check)
      - name: Run SCA (OWASP Dependency-Check)
        uses: dependency-check/Dependency-Check@main
        continue-on-error: true
        with:
          project: 'ping-pong'
          format: 'SARIF'
          output: 'dependency-check-report.sarif'

      # IaC Scan (Terraform)
      - name: Run IaC Scan (Checkov)
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          directory: .
          output_format: sarif
          output_file: checkov-results.sarif

      # Upload Reports (SARIF para GitHub Security Tab)
      - name: Upload SAST Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif

      - name: Upload SCA Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dependency-check-report.sarif

      - name: Upload IaC Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov-results.sarif

      # Notificação (opcional: Slack/Email via webhook)
      - name: Notify Critical/High Issues
        if: always()
        run: |
          echo "Security scan completed. Check GitHub Security Tab for details."
          # Adicione aqui webhooks para notificações (ex: curl para Slack)